### ISSUE TITLE
Write a README.md describing this repository

### ISSUE THREAD

**Issue by jhnoor** [jhnoor/asteroids#1]
We need to fill out the current README.md to include a detailed description of this asteroids game

Asteroids should be
* written in javascript or typescript
* asteroids game
* one ship that spawns the in middle of the screen
* arrow keys to steer and propel the ship
* black background
* asteroids should be white
* ship should be an arrow

**Comment by tarik-tasktopr** [comment]
## Step-by-step discussion

We need to create a README.md file that describes the asteroids game repository. The game should be written in JavaScript or TypeScript and include a ship that spawns in the middle of the screen. The arrow keys will be used to steer and propel the ship. The game will have a black background, white asteroids, and the ship will be an arrow.

## Plan

1. Create and populate the file README.md | To provide a detailed description of the asteroids game repository
    - Include the following information in the README.md file:
        * The game is written in JavaScript or TypeScript
        * It is an asteroids game
        * The ship spawns in the middle of the screen
        * Arrow keys are used to steer and propel the ship
        * The game has a black background
        * Asteroids are white
        * The ship is an arrow
